//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueCat.DAL.MySQL1130C
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySQL1130C : DbContext
    {
        public MySQL1130C()
            : base("name=MySQL1130C")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<pub_tfuturearbitrageinfo> pub_tfuturearbitrageinfo { get; set; }
        public virtual DbSet<pub_tfuturekind> pub_tfuturekind { get; set; }
        public virtual DbSet<pub_tfuturesinfo> pub_tfuturesinfo { get; set; }
        public virtual DbSet<pub_tstockinfo> pub_tstockinfo { get; set; }
        public virtual DbSet<yh_tclientconfig> yh_tclientconfig { get; set; }
    }
}
