//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueCat.DAL.MySQL1130C
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_tfuturekind
    {
        public int future_kind_id { get; set; }
        public int market_no { get; set; }
        public string future_kind_code { get; set; }
        public string future_kind_name { get; set; }
        public decimal marketprice_order_max { get; set; }
        public decimal limitprice_order_max { get; set; }
        public int multiple { get; set; }
        public int datecalc_type { get; set; }
        public string contract_rule { get; set; }
        public string trade_month { get; set; }
        public Nullable<int> stock_type { get; set; }
        public int future_kind_group { get; set; }
        public string night_set_flag { get; set; }
    }
}
