//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueCat.DAL.MySQL1130C
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_tfuturesinfo
    {
        public int inter_code { get; set; }
        public int future_kind_id { get; set; }
        public int sys_date { get; set; }
        public int month { get; set; }
        public int underlying_inter_code { get; set; }
        public int multiple { get; set; }
        public int last_trade_date { get; set; }
        public int last_settlement_date { get; set; }
        public int last_trade_time { get; set; }
        public decimal settle_price { get; set; }
        public decimal real_price { get; set; }
        public decimal pre_settle_price { get; set; }
        public decimal position_quantity { get; set; }
        public decimal pre_position_quantity { get; set; }
        public string market_price_enable { get; set; }
        public decimal uplimited_price { get; set; }
        public decimal downlimited_price { get; set; }
        public string future_settle_type { get; set; }
        public Nullable<int> settle_begin_date { get; set; }
        public string future_status { get; set; }
        public int left_days { get; set; }
        public decimal closing_price { get; set; }
    }
}
