//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueCat.DAL.MySQL1130C
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_tfuturearbitrageinfo
    {
        public int sys_date { get; set; }
        public int arbitrage_code { get; set; }
        public string arbi_type { get; set; }
        public Nullable<int> fir_intercode { get; set; }
        public Nullable<int> sec_intercode { get; set; }
        public string arbitrage_status { get; set; }
    }
}
