//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueCat.DAL.MySQL1130C
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_tstockinfo
    {
        public int inter_code { get; set; }
        public int sys_date { get; set; }
        public int market_no { get; set; }
        public string report_code { get; set; }
        public string stock_name { get; set; }
        public string stock_fullname { get; set; }
        public string asset_type { get; set; }
        public int stock_type { get; set; }
        public int assign_code { get; set; }
        public int asset_relative_code { get; set; }
        public int frozen_code { get; set; }
        public int match_relative1_code { get; set; }
        public decimal total_share { get; set; }
        public decimal outstanding_share { get; set; }
        public decimal pe { get; set; }
        public decimal yesterday_close_price { get; set; }
        public decimal last_price { get; set; }
        public string stock_stop_flag { get; set; }
        public decimal uplimited_amount { get; set; }
        public decimal downlimited_amount { get; set; }
        public decimal buy_unit { get; set; }
        public decimal sale_unit { get; set; }
        public string trade_platform_list { get; set; }
        public string stock_status { get; set; }
        public decimal uplimited_ratio { get; set; }
        public decimal downlimited_ratio { get; set; }
        public decimal uplimited_price { get; set; }
        public decimal downlimited_price { get; set; }
        public string price_enter_type { get; set; }
        public decimal face_value { get; set; }
        public Nullable<decimal> market_deal_amount { get; set; }
        public Nullable<decimal> market_deal_balance { get; set; }
        public int issuer_id { get; set; }
        public int publish_date { get; set; }
        public string issue_country { get; set; }
        public string trade_currency_no { get; set; }
        public string settle_currency_no { get; set; }
        public int add_date { get; set; }
        public string long_stop_flag { get; set; }
        public string stock_spell { get; set; }
        public Nullable<int> listing_date { get; set; }
        public string risk_country { get; set; }
        public string trade_flag { get; set; }
        public string transfer_mode { get; set; }
        public string private_flag { get; set; }
        public decimal pb_rate { get; set; }
        public decimal amount_per_hand { get; set; }
        public string hzjy_flag { get; set; }
        public int wx_listing_date { get; set; }
        public int limit_trade_busin { get; set; }
    }
}
