//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueCat.DAL.MySQL0224G
{
    using System;
    using System.Collections.Generic;
    
    public partial class yh_tclientconfig
    {
        public int company_id { get; set; }
        public int operator_no { get; set; }
        public string client_config_type { get; set; }
        public string config_info { get; set; }
        public int config_version { get; set; }
        public string sys_version_no { get; set; }
    }
}
